language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
- pip install --upgrade -r requirements.txt
- # the following are only needed for the examples and coverage tests
- pip install python-coveralls scikit-image coverage pytest-sugar black
- py.test --version
- python setup.py develop
script:
- NUMBA_DISABLE_JIT=1 py.test -v --cov=copt
- black --check copt
after_success: coveralls
cache:
  directories:
    - $HOME/copt_data
