steps:
- name: 'python:3.6'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/test.sh'
  timeout: 1800s  # 30 min.
- name: 'python:3.6'
  id: Doc
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/doc.sh'
  timeout: 50000s
  # waitFor: ['-']  # The '-' indicates that this step begins immediately.

- name: gcr.io/cloud-builders/gsutil
  id: Push doc
  args: ["-m", "rsync", "-r", "-c", "-d", "doc/html/_build/", "gs://copt"]

timeout: 50000s
options:
 machineType: 'N1_HIGHMEM_4'