steps:
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/test.sh'
  timeout: 1800s  # 30 min.
- name: 'python:3.7'
  id: Doc
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/doc.sh'
  timeout: 1800s  # 30 min.
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

timeout: 3200s  # 1h
