steps:
- name: 'python:3.6'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/test.sh'
  timeout: 1800s  # 30 min.
- name: 'python:3.6'
  id: Doc
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/doc.sh'
  timeout: 50000s
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'doc/_build/html/*', 'gs://openo.pt/copt/']

timeout: 50000s

artifacts:
  objects:
    location: 'gs://openo.pt/copt/'
    paths: ['doc/_build/html/doc_status.svg', 'pylint.txt', 'pylint.svg']
