steps:
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/test.sh'
- name: 'python:3.7-slim'
  id: Doc
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/doc.sh'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.