steps:
- name: 'python:3.6'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/test.sh'
  timeout: 1800s  # 30 min.
- name: 'python:3.6'
  id: Doc
  entrypoint: /bin/sh
  args:
  - -c
  - 'ci/doc.sh'
  timeout: 50000s
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

timeout: 50000s
options:
 machineType: 'N1_HIGHCPU_8'

artifacts:
  objects:
    location: 'gs://copt/'
    paths: ['doc/_build/html/*', 'doc/_build/html/*.css', 'doc/_build/html/*.png']